<?

$html_num_entities = array(
	"&#160;" => " ", # non-breaking space
	"&#161;" => "¡", # inverted exclamation mark
	"&#162;" => "¢", # cent sign
	"&#163;" => "£", # pound sign
	"&#164;" => "¤", # currency sign
	"&#165;" => "¥", # yen sign
	"&#166;" => "¦", # broken bar
	"&#167;" => "§", # section sign
	"&#168;" => "¨", # diaeresis
	"&#169;" => "©", # copyright sign
	"&#170;" => "ª", # feminine ordinal indicator
	"&#171;" => "«", # left-pointing double angle quotation mark
	"&#172;" => "¬", # not sign
	"&#173;" => "­", # soft hyphen
	"&#174;" => "®", # registered sign
	"&#175;" => "¯", # macron
	"&#176;" => "°", # degree sign
	"&#177;" => "±", # plus-minus sign
	"&#178;" => "²", # superscript two
	"&#179;" => "³", # superscript three
	"&#180;" => "´", # acute accent
	"&#181;" => "µ", # micro sign
	"&#182;" => "¶", # pilcrow sign
	"&#183;" => "·", # middle dot
	"&#184;" => "¸", # cedilla
	"&#185;" => "¹", # superscript one
	"&#186;" => "º", # masculine ordinal indicator
	"&#187;" => "»", # right-pointing double angle quotation mark
	"&#188;" => "¼", # vulgar fraction one quarter
	"&#189;" => "½", # vulgar fraction one half
	"&#190;" => "¾", # vulgar fraction three quarters
	"&#191;" => "¿", # inverted question mark
	"&#192;" => "À", # latin capital letter A with grave
	"&#193;" => "Á", # latin capital letter A with acute
	"&#194;" => "Â", # latin capital letter A with circumflex
	"&#195;" => "Ã", # latin capital letter A with tilde
	"&#196;" => "Ä", # latin capital letter A with diaeresis
	"&#197;" => "Å", # latin capital letter A with ring above
	"&#198;" => "Æ", # latin capital letter AE
	"&#199;" => "Ç", # latin capital letter C with cedilla
	"&#200;" => "È", # latin capital letter E with grave
	"&#201;" => "É", # latin capital letter E with acute
	"&#202;" => "Ê", # latin capital letter E with circumflex
	"&#203;" => "Ë", # latin capital letter E with diaeresis
	"&#204;" => "Ì", # latin capital letter I with grave
	"&#205;" => "Í", # latin capital letter I with acute
	"&#206;" => "Î", # latin capital letter I with circumflex
	"&#207;" => "Ï", # latin capital letter I with diaeresis
	"&#208;" => "Ð", # latin capital letter ETH
	"&#209;" => "Ñ", # latin capital letter N with tilde
	"&#210;" => "Ò", # latin capital letter O with grave
	"&#211;" => "Ó", # latin capital letter O with acute
	"&#212;" => "Ô", # latin capital letter O with circumflex
	"&#213;" => "Õ", # latin capital letter O with tilde
	"&#214;" => "Ö", # latin capital letter O with diaeresis
	"&#215;" => "×", # multiplication sign
	"&#216;" => "Ø", # latin capital letter O with stroke
	"&#217;" => "Ù", # latin capital letter U with grave
	"&#218;" => "Ú", # latin capital letter U with acute
	"&#219;" => "Û", # latin capital letter U with circumflex
	"&#220;" => "Ü", # latin capital letter U with diaeresis
	"&#221;" => "Ý", # latin capital letter Y with acute
	"&#222;" => "Þ", # latin capital letter THORN
	"&#223; " => "ß", # latin small letter sharp s
	"&#224;" => "à", # latin small letter a with grave
	"&#225;" => "á", # latin small letter a with acute
	"&#226;" => "â", # latin small letter a with circumflex
	"&#227;" => "ã", # latin small letter a with tilde
	"&#228;" => "ä", # latin small letter a with diaeresis
	"&#229;" => "å", # latin small letter a with ring above
	"&#230;" => "æ", # latin small letter ae
	"&#231;" => "ç", # latin small letter c with cedilla
	"&#232;" => "è", # latin small letter e with grave
	"&#233;" => "é", # latin small letter e with acute
	"&#234;" => "ê", # latin small letter e with circumflex
	"&#235;" => "ë", # latin small letter e with diaeresis
	"&#236;" => "ì", # latin small letter i with grave
	"&#237;" => "í", # latin small letter i with acute
	"&#238;" => "î", # latin small letter i with circumflex
	"&#239;" => "ï", # latin small letter i with diaeresis
	"&#240;" => "ð", # latin small letter eth
	"&#241;" => "ñ", # latin small letter n with tilde
	"&#242;" => "ò", # latin small letter o with grave
	"&#243;" => "ó", # latin small letter o with acute
	"&#244;" => "ô", # latin small letter o with circumflex
	"&#245;" => "õ", # latin small letter o with tilde
	"&#246;" => "ö", # latin small letter o with diaeresis
	"&#247;" => "÷", # division sign
	"&#248;" => "ø", # latin small letter o with stroke
	"&#249;" => "ù", # latin small letter u with grave
	"&#250;" => "ú", # latin small letter u with acute
	"&#251;" => "û", # latin small letter u with circumflex
	"&#252;" => "ü", # latin small letter u with diaeresis
	"&#253;" => "ý", # latin small letter y with acute
	"&#254;" => "þ", # latin small letter thorn
	"&#255;" => "ÿ", # latin small letter y with diaeresis
	"&#338;" => "Œ", # latin capital ligature OE
	"&#339;" => "œ", # latin small ligature oe
	"&#34;" => "\"", # quotation mark
	"&#352;" => "Š", # latin capital letter S with caron
	"&#353;" => "š", # latin small letter s with caron
	"&#376;" => "Ÿ", # latin capital letter Y with diaeresis
	"&#38;" => "&", # ampersand
	"&#402;" => "ƒ", # latin small f with hook
	"&#60;" => "<", # less-than sign
	"&#62;" => ">", # greater-than sign
	"&#710;" => "ˆ", # modifier letter circumflex accent
	"&#732;" => "˜", # small tilde
	"&#8194;" => " ", # en space
	"&#8195;" => " ", # em space
	"&#8201;" => " ", # thin space
	"&#8204;" => "‌", # zero width non-joiner
	"&#8205;" => "‍", # zero width joiner
	"&#8211;" => "–", # en dash
	"&#8212;" => "—", # em dash
	"&#8216;" => "‘", # left single quotation mark
	"&#8217;" => "’", # right single quotation mark
	"&#8218;" => "‚", # single low-9 quotation mark
	"&#8220;" => "“", # left double quotation mark
	"&#8221;" => "”", # right double quotation mark
	"&#8222;" => "„", # double low-9 quotation mark
	"&#8224;" => "†", # dagger
	"&#8225;" => "‡", # double dagger
	"&#8226;" => "•", # bullet
	"&#8230;" => "…", # horizontal ellipsis
	"&#8240;" => "‰", # per mille sign
	"&#8242;" => "′", # primeminutes
	"&#8243;" => "″", # double prime
	"&#8249;" => "‹", # single left-pointing angle quotation mark
	"&#8250;" => "›", # single right-pointing angle quotation mark
	"&#8254;" => "‾", # overline
	"&#8260;" => "⁄", # fraction slash
	"&#8364;" => "€", # euro sign
	"&#8465;" => "ℑ", # blackletter capital I
	"&#8472;" => "℘", # script capital P
	"&#8476;" => "ℜ", # blackletter capital R
	"&#8482;" => "™", # trade mark sign
	"&#8501;" => "ℵ", # alef symbol
	"&#8592;" => "←", # leftwards arrow
	"&#8593;" => "↑", # upwards arrow
	"&#8594;" => "→", # rightwards arrow
	"&#8595;" => "↓", # downwards arrow
	"&#8596;" => "↔", # left right arrow
	"&#8629;" => "↵", # downwards arrow with corner leftwards
	"&#8656;" => "⇐", # leftwards double arrow
	"&#8657;" => "⇑", # upwards double arrow
	"&#8658;" => "⇒", # rightwards double arrow
	"&#8659;" => "⇓", # downwards double arrow
	"&#8660;" => "⇔", # left right double arrow
	"&#8704;" => "∀", # for all
	"&#8706;" => "∂", # partial differential
	"&#8707;" => "∃", # there exists
	"&#8709;" => "∅", # empty set
	"&#8711;" => "∇", # nabla
	"&#8712;" => "∈", # element of
	"&#8713;" => "∉", # not an element of
	"&#8715;" => "∋", # contains as member
	"&#8719;" => "∏", # n-ary product
	"&#8721;" => "∑", # n-ary sumation
	"&#8722;" => "−", # minus sign
	"&#8727;" => "∗", # asterisk operator
	"&#8730;" => "√", # square root
	"&#8733;" => "∝", # proportional to
	"&#8734;" => "∞", # infinity
	"&#8736;" => "∠", # angle
	"&#8743;" => "∧", # logical and
	"&#8744;" => "∨", # logical or
	"&#8745;" => "∩", # intersection
	"&#8746;" => "∪", # union
	"&#8747;" => "∫", # integral
	"&#8756;" => "∴", # therefore
	"&#8764;" => "∼", # tilde operator
	"&#8773;" => "≅", # approximately equal to
	"&#8776;" => "≈", # almost equal to
	"&#8800;" => "≠", # not equal to
	"&#8801;" => "≡", # identical to
	"&#8804;" => "≤", # less-than or equal to
	"&#8805;" => "≥", # greater-than or equal to
	"&#8834;" => "⊂", # subset of
	"&#8835;" => "⊃", # superset of
	"&#8836;" => "⊄", # not a subset of
	"&#8838;" => "⊆", # subset of or equal to
	"&#8839;" => "⊇", # superset of or equal to
	"&#8853;" => "⊕", # circled plus
	"&#8855;" => "⊗", # circled times
	"&#8869;" => "⊥", # up tack
	"&#8901;" => "⋅", # dot operator
	"&#8968;" => "⌈", # left ceiling
	"&#8969;" => "⌉", # right ceiling
	"&#8970;" => "⌊", # left floor
	"&#8971;" => "⌋", # right floor
	"&#9001;" => "〈", # left-pointing angle bracket
	"&#9002;" => "〉", # right-pointing angle bracket
	"&#913;" => "Α", # greek capital letter alpha
	"&#914;" => "Β", # greek capital letter beta
	"&#915;" => "Γ", # greek capital letter gamma
	"&#916;" => "Δ", # greek capital letter delta
	"&#917;" => "Ε", # greek capital letter epsilon
	"&#918;" => "Ζ", # greek capital letter zeta
	"&#919;" => "Η", # greek capital letter eta
	"&#920;" => "Θ", # greek capital letter theta
	"&#921;" => "Ι", # greek capital letter iota
	"&#922;" => "Κ", # greek capital letter kappa
	"&#923;" => "Λ", # greek capital letter lambda
	"&#924;" => "Μ", # greek capital letter mu
	"&#925;" => "Ν", # greek capital letter nu
	"&#926;" => "Ξ", # greek capital letter xi
	"&#927;" => "Ο", # greek capital letter omicron
	"&#928;" => "Π", # greek capital letter pi
	"&#929;" => "Ρ", # greek capital letter rho
	"&#931;" => "Σ", # greek capital letter sigma
	"&#932;" => "Τ", # greek capital letter tau
	"&#933;" => "Υ", # greek capital letter upsilon
	"&#934;" => "Φ", # greek capital letter phi
	"&#935;" => "Χ", # greek capital letter chi
	"&#936;" => "Ψ", # greek capital letter psi
	"&#937;" => "Ω", # greek capital letter omega
	"&#945;" => "α", # greek small letter alpha
	"&#946;" => "β", # greek small letter beta
	"&#947;" => "γ", # greek small letter gamma
	"&#948;" => "δ", # greek small letter delta
	"&#949;" => "ε", # greek small letter epsilon
	"&#950;" => "ζ", # greek small letter zeta
	"&#951;" => "η", # greek small letter eta
	"&#952;" => "θ", # greek small letter theta
	"&#953;" => "ι", # greek small letter iota
	"&#954;" => "κ", # greek small letter kappa
	"&#955;" => "λ", # greek small letter lambda
	"&#956;" => "μ", # greek small letter mu
	"&#957;" => "ν", # greek small letter nu
	"&#958;" => "ξ", # greek small letter xi
	"&#959;" => "ο", # greek small letter omicron
	"&#960;" => "π", # greek small letter pi
	"&#961;" => "ρ", # greek small letter rho
	"&#962;" => "ς", # greek small letter final sigma
	"&#963;" => "σ", # greek small letter sigma
	"&#964;" => "τ", # greek small letter tau
	"&#965;" => "υ", # greek small letter upsilon
	"&#966;" => "φ", # greek small letter phi
	"&#9674;" => "◊", # lozenge
	"&#967;" => "χ", # greek small letter chi
	"&#968;" => "ψ", # greek small letter psi
	"&#969;" => "ω", # greek small letter omega
	"&#977;" => "ϑ", # greek small letter theta symbol
	"&#978;" => "ϒ", # greek upsilon with hook symbol
	"&#9824;" => "♠", # black spade suit
	"&#9827;" => "♣", # black club suit
	"&#9829;" => "♥", # black heart suit
	"&#982;" => "ϖ", # greek pi symbol
	"&#9830;" => "♦", # black diamond suit

	# common non-standard entities
	"&#038;" => "&",
	"&#145;" => "‘",
	"&#146;" => "’",
	"&#147;" => "“",
	"&#148;" => "”",
	"&#150;" => "–",
	"&#151;" => "—",
	"&#0171;" => "«",
	"&#0187;" => "»",
);

# på http://www.danshort.com/HTMLentities/index.php?w=dingb finns ännu fler entiteter (dingbats)

$html_alpha_entities = array(
	"&AElig;" => "Æ", # latin capital letter AE
	"&Aacute;" => "Á", # latin capital letter A with acute
	"&Acirc;" => "Â", # latin capital letter A with circumflex
	"&Agrave;" => "À", # latin capital letter A with grave
	"&Alpha;" => "Α", # greek capital letter alpha
	"&Aring;" => "Å", # latin capital letter A with ring above
	"&Atilde;" => "Ã", # latin capital letter A with tilde
	"&Auml;" => "Ä", # latin capital letter A with diaeresis
	"&Beta;" => "Β", # greek capital letter beta
	"&Ccedil;" => "Ç", # latin capital letter C with cedilla
	"&Chi;" => "Χ", # greek capital letter chi
	"&Dagger;" => "‡", # double dagger
	"&Delta;" => "Δ", # greek capital letter delta
	"&ETH;" => "Ð", # latin capital letter ETH
	"&Eacute;" => "É", # latin capital letter E with acute
	"&Ecirc;" => "Ê", # latin capital letter E with circumflex
	"&Egrave;" => "È", # latin capital letter E with grave
	"&Epsilon;" => "Ε", # greek capital letter epsilon
	"&Eta;" => "Η", # greek capital letter eta
	"&Euml;" => "Ë", # latin capital letter E with diaeresis
	"&Gamma;" => "Γ", # greek capital letter gamma
	"&Iacute;" => "Í", # latin capital letter I with acute
	"&Icirc;" => "Î", # latin capital letter I with circumflex
	"&Igrave;" => "Ì", # latin capital letter I with grave
	"&Iota;" => "Ι", # greek capital letter iota
	"&Iuml;" => "Ï", # latin capital letter I with diaeresis
	"&Kappa;" => "Κ", # greek capital letter kappa
	"&Lambda;" => "Λ", # greek capital letter lambda
	"&Mu;" => "Μ", # greek capital letter mu
	"&Ntilde;" => "Ñ", # latin capital letter N with tilde
	"&Nu;" => "Ν", # greek capital letter nu
	"&OElig;" => "Œ", # latin capital ligature OE
	"&Oacute;" => "Ó", # latin capital letter O with acute
	"&Ocirc;" => "Ô", # latin capital letter O with circumflex
	"&Ograve;" => "Ò", # latin capital letter O with grave
	"&Omega;" => "Ω", # greek capital letter omega
	"&Omicron;" => "Ο", # greek capital letter omicron
	"&Oslash;" => "Ø", # latin capital letter O with stroke
	"&Otilde;" => "Õ", # latin capital letter O with tilde
	"&Ouml;" => "Ö", # latin capital letter O with diaeresis
	"&Phi;" => "Φ", # greek capital letter phi
	"&Pi;" => "Π", # greek capital letter pi
	"&Prime;" => "″", # double prime
	"&Psi;" => "Ψ", # greek capital letter psi
	"&Rho;" => "Ρ", # greek capital letter rho
	"&Scaron;" => "Š", # latin capital letter S with caron
	"&Sigma;" => "Σ", # greek capital letter sigma
	"&THORN;" => "Þ", # latin capital letter THORN
	"&Tau;" => "Τ", # greek capital letter tau
	"&Theta;" => "Θ", # greek capital letter theta
	"&Uacute;" => "Ú", # latin capital letter U with acute
	"&Ucirc;" => "Û", # latin capital letter U with circumflex
	"&Ugrave;" => "Ù", # latin capital letter U with grave
	"&Upsilon;" => "Υ", # greek capital letter upsilon
	"&Uuml;" => "Ü", # latin capital letter U with diaeresis
	"&Xi;" => "Ξ", # greek capital letter xi
	"&Yacute;" => "Ý", # latin capital letter Y with acute
	"&Yuml;" => "Ÿ", # latin capital letter Y with diaeresis
	"&Zeta;" => "Ζ", # greek capital letter zeta
	"&aacute;" => "á", # latin small letter a with acute
	"&acirc;" => "â", # latin small letter a with circumflex
	"&acute;" => "´", # acute accent
	"&aelig;" => "æ", # latin small letter ae
	"&agrave;" => "à", # latin small letter a with grave
	"&alefsym;" => "ℵ", # alef symbol
	"&alpha;" => "α", # greek small letter alpha
	"&amp;" => "&", # ampersand
	"&and;" => "∧", # logical and
	"&ang;" => "∠", # angle
	"&aring;" => "å", # latin small letter a with ring above
	"&asymp;" => "≈", # almost equal to
	"&atilde;" => "ã", # latin small letter a with tilde
	"&auml;" => "ä", # latin small letter a with diaeresis
	"&bdquo;" => "„", # double low-9 quotation mark
	"&beta;" => "β", # greek small letter beta
	"&brvbar;" => "¦", # broken bar
	"&bull;" => "•", # bullet
	"&cap;" => "∩", # intersection
	"&ccedil;" => "ç", # latin small letter c with cedilla
	"&cedil;" => "¸", # cedilla
	"&cent;" => "¢", # cent sign
	"&chi;" => "χ", # greek small letter chi
	"&circ;" => "ˆ", # modifier letter circumflex accent
	"&clubs;" => "♣", # black club suit
	"&cong;" => "≅", # approximately equal to
	"&copy;" => "©", # copyright sign
	"&crarr;" => "↵", # downwards arrow with corner leftwards
	"&cup;" => "∪", # union
	"&curren;" => "¤", # currency sign
	"&dArr;" => "⇓", # downwards double arrow
	"&dagger;" => "†", # dagger
	"&darr;" => "↓", # downwards arrow
	"&deg;" => "°", # degree sign
	"&delta;" => "δ", # greek small letter delta
	"&diams;" => "♦", # black diamond suit
	"&divide;" => "÷", # division sign
	"&eacute;" => "é", # latin small letter e with acute
	"&ecirc;" => "ê", # latin small letter e with circumflex
	"&egrave;" => "è", # latin small letter e with grave
	"&empty;" => "∅", # empty set
	"&emsp;" => " ", # em space
	"&ensp;" => " ", # en space
	"&epsilon;" => "ε", # greek small letter epsilon
	"&equiv;" => "≡", # identical to
	"&eta;" => "η", # greek small letter eta
	"&eth;" => "ð", # latin small letter eth
	"&euml;" => "ë", # latin small letter e with diaeresis
	"&euro;" => "€", # euro sign
	"&exist;" => "∃", # there exists
	"&fnof;" => "ƒ", # latin small f with hook
	"&forall;" => "∀", # for all
	"&frac12;" => "½", # vulgar fraction one half
	"&frac14;" => "¼", # vulgar fraction one quarter
	"&frac34;" => "¾", # vulgar fraction three quarters
	"&frasl;" => "⁄", # fraction slash
	"&gamma;" => "γ", # greek small letter gamma
	"&ge;" => "≥", # greater-than or equal to
	"&gt;" => ">", # greater-than sign
	"&hArr;" => "⇔", # left right double arrow
	"&harr;" => "↔", # left right arrow
	"&hearts;" => "♥", # black heart suit
	"&hellip;" => "…", # horizontal ellipsis
	"&iacute;" => "í", # latin small letter i with acute
	"&icirc;" => "î", # latin small letter i with circumflex
	"&iexcl;" => "¡", # inverted exclamation mark
	"&igrave;" => "ì", # latin small letter i with grave
	"&image;" => "ℑ", # blackletter capital I
	"&infin;" => "∞", # infinity
	"&int;" => "∫", # integral
	"&iota;" => "ι", # greek small letter iota
	"&iquest;" => "¿", # inverted question mark
	"&isin;" => "∈", # element of
	"&iuml;" => "ï", # latin small letter i with diaeresis
	"&kappa;" => "κ", # greek small letter kappa
	"&lArr;" => "⇐", # leftwards double arrow
	"&lambda;" => "λ", # greek small letter lambda
	"&lang;" => "〈", # left-pointing angle bracket
	"&laquo;" => "«", # left-pointing double angle quotation mark
	"&larr;" => "←", # leftwards arrow
	"&lceil;" => "⌈", # left ceiling
	"&ldquo;" => "“", # left double quotation mark
	"&le;" => "≤", # less-than or equal to
	"&lfloor;" => "⌊", # left floor
	"&lowast;" => "∗", # asterisk operator
	"&loz;" => "◊", # lozenge
	"&lsaquo;" => "‹", # single left-pointing angle quotation mark
	"&lsquo;" => "‘", # left single quotation mark
	"&lt;" => "<", # less-than sign
	"&macr;" => "¯", # macron
	"&mdash;" => "—", # em dash
	"&micro;" => "µ", # micro sign
	"&middot;" => "·", # middle dot
	"&minus;" => "−", # minus sign
	"&mu;" => "μ", # greek small letter mu
	"&nabla;" => "∇", # nabla
	"&nbsp;" => " ", # non-breaking space
	"&ndash;" => "–", # en dash
	"&ne;" => "≠", # not equal to
	"&ni;" => "∋", # contains as member
	"&not;" => "¬", # not sign
	"&notin;" => "∉", # not an element of
	"&nsub;" => "⊄", # not a subset of
	"&ntilde;" => "ñ", # latin small letter n with tilde
	"&nu;" => "ν", # greek small letter nu
	"&oacute;" => "ó", # latin small letter o with acute
	"&ocirc;" => "ô", # latin small letter o with circumflex
	"&oelig;" => "œ", # latin small ligature oe
	"&ograve;" => "ò", # latin small letter o with grave
	"&oline;" => "‾", # overline
	"&omega;" => "ω", # greek small letter omega
	"&omicron;" => "ο", # greek small letter omicron
	"&oplus;" => "⊕", # circled plus
	"&or;" => "∨", # logical or
	"&ordf;" => "ª", # feminine ordinal indicator
	"&ordm;" => "º", # masculine ordinal indicator
	"&oslash;" => "ø", # latin small letter o with stroke
	"&otilde;" => "õ", # latin small letter o with tilde
	"&otimes;" => "⊗", # circled times
	"&ouml;" => "ö", # latin small letter o with diaeresis
	"&para;" => "¶", # pilcrow sign
	"&part;" => "∂", # partial differential
	"&permil;" => "‰", # per mille sign
	"&perp;" => "⊥", # up tack
	"&phi;" => "φ", # greek small letter phi
	"&pi;" => "π", # greek small letter pi
	"&piv;" => "ϖ", # greek pi symbol
	"&plusmn;" => "±", # plus-minus sign
	"&pound;" => "£", # pound sign
	"&prime;" => "′", # primeminutes
	"&prod;" => "∏", # n-ary product
	"&prop;" => "∝", # proportional to
	"&psi;" => "ψ", # greek small letter psi
	"&quot;" => "\"", # quotation mark
	"&rArr;" => "⇒", # rightwards double arrow
	"&radic;" => "√", # square root
	"&rang;" => "〉", # right-pointing angle bracket
	"&raquo;" => "»", # right-pointing double angle quotation mark
	"&rarr;" => "→", # rightwards arrow
	"&rceil;" => "⌉", # right ceiling
	"&rdquo;" => "”", # right double quotation mark
	"&real;" => "ℜ", # blackletter capital R
	"&reg;" => "®", # registered sign
	"&rfloor;" => "⌋", # right floor
	"&rho;" => "ρ", # greek small letter rho
	"&rsaquo;" => "›", # single right-pointing angle quotation mark
	"&rsquo;" => "’", # right single quotation mark
	"&sbquo;" => "‚", # single low-9 quotation mark
	"&scaron;" => "š", # latin small letter s with caron
	"&sdot;" => "⋅", # dot operator
	"&sect;" => "§", # section sign
	"&shy;" => "­", # soft hyphen
	"&sigma;" => "σ", # greek small letter sigma
	"&sigmaf;" => "ς", # greek small letter final sigma
	"&sim;" => "∼", # tilde operator
	"&spades;" => "♠", # black spade suit
	"&sub;" => "⊂", # subset of
	"&sube;" => "⊆", # subset of or equal to
	"&sum;" => "∑", # n-ary sumation
	"&sup1;" => "¹", # superscript one
	"&sup2;" => "²", # superscript two
	"&sup3;" => "³", # superscript three
	"&sup;" => "⊃", # superset of
	"&supe;" => "⊇", # superset of or equal to
	"&szlig; " => "ß", # latin small letter sharp s
	"&tau;" => "τ", # greek small letter tau
	"&there4;" => "∴", # therefore
	"&theta;" => "θ", # greek small letter theta
	"&thetasym;" => "ϑ", # greek small letter theta symbol
	"&thinsp;" => " ", # thin space
	"&thorn;" => "þ", # latin small letter thorn
	"&tilde;" => "˜", # small tilde
	"&times;" => "×", # multiplication sign
	"&trade;" => "™", # trade mark sign
	"&uArr;" => "⇑", # upwards double arrow
	"&uacute;" => "ú", # latin small letter u with acute
	"&uarr;" => "↑", # upwards arrow
	"&ucirc;" => "û", # latin small letter u with circumflex
	"&ugrave;" => "ù", # latin small letter u with grave
	"&uml;" => "¨", # diaeresis
	"&upsih;" => "ϒ", # greek upsilon with hook symbol
	"&upsilon;" => "υ", # greek small letter upsilon
	"&uuml;" => "ü", # latin small letter u with diaeresis
	"&weierp;" => "℘", # script capital P
	"&xi;" => "ξ", # greek small letter xi
	"&yacute;" => "ý", # latin small letter y with acute
	"&yen;" => "¥", # yen sign
	"&yuml;" => "ÿ", # latin small letter y with diaeresis
	"&zeta;" => "ζ", # greek small letter zeta
	"&zwj;" => "‍", # zero width joiner
	"&zwnj;" => "‌", # zero width non-joiner
);


# &auml; --> ä
function decode_html_entities($string)
{
	global $html_num_entities, $html_alpha_entities;

	$codes1 = array_keys($html_num_entities);
	$chars1 = array_values($html_num_entities);

	$codes2 = array_keys($html_alpha_entities);
	$chars2 = array_values($html_alpha_entities);

	$string = str_replace($codes1, $chars1, $string);
	$string = str_replace($codes2, $chars2, $string);

	return $string;
}

# ä --> &auml;
function encode_html_entities($string)
{
	global $html_num_entities, $html_alpha_entities;

	$codes = array_keys($html_alpha_entities);
	$chars = array_values($html_alpha_entities);

	$string = str_replace($chars, $codes, $string);
	$string = preg_replace("/&amp;(#\d+|[\da-zA-Z]+);/", "&\\1;", $string);
	$string = str_replace("&nbsp;", " ", $string);

	return $string;
}

?>
